package store

import (
	"time"

	"github.com/choresync/backend/internal/models"
)

func strPtr(s string) *string {
	return &s
}

func intPtr(i int) *int {
	return &i
}

func boolPtr(b bool) *bool {
	return &b
}

func getInitialData() (
	[]models.Household,
	[]models.Member,
	[]models.Chore,
	[]models.ChoreCompletion,
	[]models.ChoreSwapRequest,
	[]models.RewardItem,
	[]models.RewardRedemption,
	[]models.ActivityLog,
	[]models.ChoreComment,
) {
	now := time.Now().UTC()
	nowISO := now.Format(time.RFC3339)

	households := []models.Household{
		{
			ID:         "h-roommates",
			Name:       "Apartment 4B",
			InviteCode: "APT4B-SHARE",
			Settings: models.HouseholdSettings{
				DefaultMode: models.HouseholdModeFlatmate,
				AllowSwaps:  true,
				Timezone:    "America/New_York",
				AdminPIN:    "1234",
			},
			CreatedAt: now.Add(-30 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt: nowISO,
		},
		{
			ID:         "h-family",
			Name:       "The Miller Family",
			InviteCode: "MILLER-HOME",
			Settings: models.HouseholdSettings{
				DefaultMode: models.HouseholdModeFamily,
				AllowSwaps:  true,
				Timezone:    "America/New_York",
				AdminPIN:    "1234",
			},
			CreatedAt: now.Add(-60 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt: nowISO,
		},
		{
			ID:         "h-couple",
			Name:       "Alex & Sam",
			InviteCode: "COUPLE-NEST",
			Settings: models.HouseholdSettings{
				DefaultMode: models.HouseholdModeCasual,
				AllowSwaps:  false,
				Timezone:    "America/New_York",
				AdminPIN:    "1234",
			},
			CreatedAt: now.Add(-15 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt: nowISO,
		},
	}

	members := []models.Member{
		// Roommates
		{
			ID:                "m-sarah",
			HouseholdID:       "h-roommates",
			Name:              "Sarah Chen",
			Email:             strPtr("sarah@example.com"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleAdmin,
			PointsBalance:     145,
			TotalPointsEarned: 420,
			Streak:            6,
			CreatedAt:         now.Add(-30 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "m-liam",
			HouseholdID:       "h-roommates",
			Name:              "Liam Vance",
			Email:             strPtr("liam@example.com"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleMember,
			PointsBalance:     85,
			TotalPointsEarned: 310,
			Streak:            3,
			CreatedAt:         now.Add(-30 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "m-maya",
			HouseholdID:       "h-roommates",
			Name:              "Maya Patel",
			Email:             strPtr("maya@example.com"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleMember,
			PointsBalance:     190,
			TotalPointsEarned: 490,
			Streak:            9,
			CreatedAt:         now.Add(-30 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "m-noah",
			HouseholdID:       "h-roommates",
			Name:              "Noah Brooks",
			Email:             strPtr("noah@example.com"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleMember,
			PointsBalance:     60,
			TotalPointsEarned: 220,
			Streak:            1,
			CreatedAt:         now.Add(-20 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		// Family
		{
			ID:                "m-david-fam",
			HouseholdID:       "h-family",
			Name:              "David (Dad)",
			Email:             strPtr("david@miller.family"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleAdmin,
			PointsBalance:     320,
			TotalPointsEarned: 890,
			Streak:            14,
			CreatedAt:         now.Add(-60 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "m-sarah-fam",
			HouseholdID:       "h-family",
			Name:              "Sarah (Mom)",
			Email:             strPtr("sarah@miller.family"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleAdmin,
			PointsBalance:     290,
			TotalPointsEarned: 760,
			Streak:            12,
			CreatedAt:         now.Add(-60 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "m-leo-kid",
			HouseholdID:       "h-family",
			Name:              "Leo (10y)",
			Email:             strPtr("leo@miller.family"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleChild,
			PointsBalance:     75,
			TotalPointsEarned: 230,
			Streak:            5,
			CreatedAt:         now.Add(-60 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "m-emma-kid",
			HouseholdID:       "h-family",
			Name:              "Emma (8y)",
			Email:             strPtr("emma@miller.family"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1519456264917-42d0aa2e0625?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleChild,
			PointsBalance:     110,
			TotalPointsEarned: 280,
			Streak:            8,
			CreatedAt:         now.Add(-60 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		// Couple
		{
			ID:                "m-alex",
			HouseholdID:       "h-couple",
			Name:              "Alex Rivera",
			Email:             strPtr("alex@example.com"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleMember,
			PointsBalance:     150,
			TotalPointsEarned: 450,
			Streak:            5,
			CreatedAt:         now.Add(-15 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "m-sam",
			HouseholdID:       "h-couple",
			Name:              "Sam Taylor",
			Email:             strPtr("sam@example.com"),
			AvatarURL:         strPtr("https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80"),
			Role:              models.MemberRoleMember,
			PointsBalance:     180,
			TotalPointsEarned: 490,
			Streak:            7,
			CreatedAt:         now.Add(-15 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
	}

	chores := []models.Chore{
		// Roommates
		{
			ID:                   "c-recycling-rr",
			HouseholdID:          "h-roommates",
			Title:                "Recycling & Garbage to Curb",
			Description:          strPtr("Separate glass, plastic, and cardboard. Roll bins to curb by 8 PM Tuesday."),
			Category:             models.ChoreCategoryMaintenance,
			EffortPoints:         20,
			AssignmentType:       models.ChoreAssignmentRoundRobin,
			CurrentAssigneeID:    strPtr("m-liam"),
			RotationMemberIDs:    []string{"m-sarah", "m-liam", "m-maya", "m-noah"},
			CurrentRotationIndex: intPtr(1),
			RecurrenceType:       models.ChoreRecurrenceWeekly,
			RecurrenceRule:       &models.ChoreRecurrenceRule{Days: []string{"tue"}},
			DueDate:              strPtr(now.Add(18 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:     false,
			RequiresProof:        false,
			Status:               models.ChoreStatusAssigned,
			CreatedBy:            "m-sarah",
			CreatedAt:            now.Add(-7 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:            nowISO,
		},
		{
			ID:                "c-kitchen-deep",
			HouseholdID:       "h-roommates",
			Title:             "Deep Clean Kitchen Counters & Stovetop",
			Description:       strPtr("Wipe all counters with disinfectant, degrease stovetop burners, polish sink."),
			Category:          models.ChoreCategoryKitchen,
			EffortPoints:      25,
			AssignmentType:    models.ChoreAssignmentDirect,
			CurrentAssigneeID: strPtr("m-sarah"),
			RecurrenceType:    models.ChoreRecurrenceWeekly,
			DueDate:           strPtr(now.Add(48 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:  false,
			RequiresProof:     false,
			Status:            models.ChoreStatusAssigned,
			CreatedBy:         "m-sarah",
			CreatedAt:         now.Add(-5 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "c-vacuum-living",
			HouseholdID:       "h-roommates",
			Title:             "Vacuum Living Room & Dust Shelves",
			Description:       strPtr("Move chairs, vacuum under sofa edge, dust TV console and bookshelves."),
			Category:          models.ChoreCategoryCleaning,
			EffortPoints:      15,
			AssignmentType:    models.ChoreAssignmentDirect,
			CurrentAssigneeID: strPtr("m-liam"),
			RecurrenceType:    models.ChoreRecurrenceWeekly,
			DueDate:           strPtr(now.Add(-14 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:  false,
			RequiresProof:     false,
			Status:            models.ChoreStatusOverdue,
			CreatedBy:         "m-sarah",
			CreatedAt:         now.Add(-3 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                   "c-bathroom-mop",
			HouseholdID:          "h-roommates",
			Title:                "Scrub Shower & Mop Bathroom Floor",
			Description:          strPtr("Scrub tiles, empty shower drain, disinfect toilet, and mop floor."),
			Category:             models.ChoreCategoryCleaning,
			EffortPoints:         30,
			AssignmentType:       models.ChoreAssignmentRoundRobin,
			CurrentAssigneeID:    strPtr("m-maya"),
			RotationMemberIDs:    []string{"m-maya", "m-noah", "m-sarah", "m-liam"},
			CurrentRotationIndex: intPtr(0),
			RecurrenceType:       models.ChoreRecurrenceWeekly,
			DueDate:              strPtr(now.Add(96 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:     false,
			RequiresProof:        false,
			Status:               models.ChoreStatusAssigned,
			CreatedBy:            "m-sarah",
			CreatedAt:            now.Add(-2 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:            nowISO,
		},
		{
			ID:                "c-balcony-sweep",
			HouseholdID:       "h-roommates",
			Title:             "Water Plants & Sweep Balcony",
			Description:       strPtr("Water fern and herb garden, sweep fallen leaves and tidy outdoor chairs."),
			Category:          models.ChoreCategoryYard,
			EffortPoints:      10,
			AssignmentType:    models.ChoreAssignmentOpenPool,
			CurrentAssigneeID: nil,
			RecurrenceType:    models.ChoreRecurrenceDaily,
			DueDate:           strPtr(now.Add(6 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:  false,
			RequiresProof:     false,
			Status:            models.ChoreStatusUnassigned,
			CreatedBy:         "m-maya",
			CreatedAt:         now.Add(-1 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		// Family
		{
			ID:                "c-fam-bedroom-leo",
			HouseholdID:       "h-family",
			Title:             "Clean Up Bedroom & Put Away Toys",
			Description:       strPtr("Make bed, put Lego boxes back in closet, hang up clean clothes."),
			Category:          models.ChoreCategoryCleaning,
			EffortPoints:      15,
			AssignmentType:    models.ChoreAssignmentDirect,
			CurrentAssigneeID: strPtr("m-leo-kid"),
			RecurrenceType:    models.ChoreRecurrenceDaily,
			DueDate:           strPtr(now.Add(-2 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:  true,
			RequiresProof:     true,
			Status:            models.ChoreStatusPendingApproval,
			CreatedBy:         "m-sarah-fam",
			CreatedAt:         now.Add(-1 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                   "c-fam-dog-walk",
			HouseholdID:          "h-family",
			Title:                "Walk Buster & Refill Dog Bowls",
			Description:          strPtr("20-minute walk around the park. Wash food bowl and add clean cold water."),
			Category:             models.ChoreCategoryPets,
			EffortPoints:         20,
			AssignmentType:       models.ChoreAssignmentRoundRobin,
			CurrentAssigneeID:    strPtr("m-emma-kid"),
			RotationMemberIDs:    []string{"m-leo-kid", "m-emma-kid"},
			CurrentRotationIndex: intPtr(1),
			RecurrenceType:       models.ChoreRecurrenceDaily,
			DueDate:              strPtr(now.Add(5 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:     true,
			RequiresProof:        true,
			Status:               models.ChoreStatusAssigned,
			CreatedBy:            "m-david-fam",
			CreatedAt:            now.Add(-2 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:            nowISO,
		},
		{
			ID:                "c-fam-lawn",
			HouseholdID:       "h-family",
			Title:             "Mow Front Lawn & Rake Grass",
			Description:       strPtr("Use the electric mower on level 3, edge sidewalk, and put clippings in compost bin."),
			Category:          models.ChoreCategoryYard,
			EffortPoints:      35,
			AssignmentType:    models.ChoreAssignmentDirect,
			CurrentAssigneeID: strPtr("m-david-fam"),
			RecurrenceType:    models.ChoreRecurrenceWeekly,
			DueDate:           strPtr(now.Add(72 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:  false,
			RequiresProof:     false,
			Status:            models.ChoreStatusAssigned,
			CreatedBy:         "m-sarah-fam",
			CreatedAt:         now.Add(-2 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "c-fam-dishwasher",
			HouseholdID:       "h-family",
			Title:             "Unload Clean Dishwasher",
			Description:       strPtr("Put plates, bowls, cups, and cutlery into their respective cupboards."),
			Category:          models.ChoreCategoryKitchen,
			EffortPoints:      10,
			AssignmentType:    models.ChoreAssignmentOpenPool,
			CurrentAssigneeID: nil,
			RecurrenceType:    models.ChoreRecurrenceDaily,
			DueDate:           strPtr(now.Add(8 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:  true,
			RequiresProof:     false,
			Status:            models.ChoreStatusUnassigned,
			CreatedBy:         "m-sarah-fam",
			CreatedAt:         now.Add(-1 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		// Couple
		{
			ID:                "c-couple-groceries",
			HouseholdID:       "h-couple",
			Title:             "Weekend Farmers Market Run",
			Description:       strPtr("Pick up eggs, sourdough bread, organic greens, and oat milk."),
			Category:          models.ChoreCategoryOther,
			EffortPoints:      20,
			AssignmentType:    models.ChoreAssignmentOpenPool,
			CurrentAssigneeID: nil,
			RecurrenceType:    models.ChoreRecurrenceWeekly,
			DueDate:           strPtr(now.Add(24 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:  false,
			RequiresProof:     false,
			Status:            models.ChoreStatusUnassigned,
			CreatedBy:         "m-alex",
			CreatedAt:         now.Add(-1 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
		{
			ID:                "c-couple-sheets",
			HouseholdID:       "h-couple",
			Title:             "Wash & Change Bed Linens",
			Description:       strPtr("Fitted sheet, duvet cover, and pillowcases. Wash on warm, hang to dry."),
			Category:          models.ChoreCategoryCleaning,
			EffortPoints:      15,
			AssignmentType:    models.ChoreAssignmentDirect,
			CurrentAssigneeID: strPtr("m-sam"),
			RecurrenceType:    models.ChoreRecurrenceWeekly,
			DueDate:           strPtr(now.Add(12 * time.Hour).Format(time.RFC3339)),
			RequiresApproval:  false,
			RequiresProof:     false,
			Status:            models.ChoreStatusAssigned,
			CreatedBy:         "m-alex",
			CreatedAt:         now.Add(-3 * 24 * time.Hour).Format(time.RFC3339),
			UpdatedAt:         nowISO,
		},
	}

	completions := []models.ChoreCompletion{
		{
			ID:            "comp-seed-leo-1",
			ChoreID:       "c-fam-bedroom-leo",
			HouseholdID:   "h-family",
			MemberID:      "m-leo-kid",
			Status:        models.CompletionStatusPendingApproval,
			ProofNotes:    strPtr("I made the bed neat, organized my Lego sets, and put all the shoes away!"),
			ProofPhotoURL: strPtr("https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80"),
			PointsAwarded: 15,
			CompletedAt:   now.Add(-45 * time.Minute).Format(time.RFC3339),
		},
	}

	swaps := []models.ChoreSwapRequest{
		{
			ID:             "swap-seed-1",
			HouseholdID:    "h-roommates",
			ChoreID:        "c-vacuum-living",
			RequesterID:    "m-liam",
			TargetMemberID: strPtr("m-maya"),
			Status:         models.SwapStatusPending,
			Reason:         strPtr("I have a big mid-term exam tomorrow night; could anyone take this? I will cover recycling next week!"),
			CreatedAt:      now.Add(-5 * time.Hour).Format(time.RFC3339),
		},
	}

	rewards := []models.RewardItem{
		// Roommates
		{
			ID:          "rew-room-coffee",
			HouseholdID: "h-roommates",
			Title:       "Roommate Buys Your Fancy Coffee",
			Description: "Next coffee run is on the house! Order whatever oat latte or pastry you like.",
			PointsCost:  60,
			Icon:        strPtr("Coffee"),
			IsActive:    true,
		},
		{
			ID:          "rew-room-dishes-pass",
			HouseholdID: "h-roommates",
			Title:       "Exemption from Dishes for a Day",
			Description: "Get a full 24-hour pass where your housemates clean up all cooking dishes.",
			PointsCost:  90,
			Icon:        strPtr("Sparkles"),
			IsActive:    true,
		},
		{
			ID:          "rew-room-movie",
			HouseholdID: "h-roommates",
			Title:       "Sole Pick for Apartment Movie Night",
			Description: "Zero debates or vetoes: you pick the movie and Friday snack.",
			PointsCost:  50,
			Icon:        strPtr("Tv"),
			IsActive:    true,
		},
		// Family
		{
			ID:          "rew-fam-bedtime",
			HouseholdID: "h-family",
			Title:       "30-Minute Late Bedtime Pass",
			Description: "Stay up an extra 30 minutes reading or watching your favorite cartoon.",
			PointsCost:  40,
			Icon:        strPtr("Moon"),
			IsActive:    true,
		},
		{
			ID:          "rew-fam-icecream",
			HouseholdID: "h-family",
			Title:       "Ice Cream Sundae Trip",
			Description: "Trip to the local creamery with double scoops and two toppings of your choice!",
			PointsCost:  75,
			Icon:        strPtr("IceCream"),
			IsActive:    true,
		},
		{
			ID:          "rew-fam-game",
			HouseholdID: "h-family",
			Title:       "Choose Sunday Family Board Game",
			Description: "Pick the game we all play together after Sunday dinner.",
			PointsCost:  30,
			Icon:        strPtr("Gamepad2"),
			IsActive:    true,
		},
		// Couple
		{
			ID:          "rew-couple-dinner",
			HouseholdID: "h-couple",
			Title:       "Partner Cooks Your Favorite Dinner",
			Description: "Sit back with a beverage while your partner cooks any meal you crave.",
			PointsCost:  80,
			Icon:        strPtr("UtensilsCrossed"),
			IsActive:    true,
		},
		{
			ID:          "rew-couple-massage",
			HouseholdID: "h-couple",
			Title:       "20-Minute Shoulder & Back Massage",
			Description: "Relaxing massage with soothing music and essential oils.",
			PointsCost:  70,
			Icon:        strPtr("HeartHandshake"),
			IsActive:    true,
		},
	}

	redemptions := []models.RewardRedemption{
		{
			ID:           "red-seed-1",
			HouseholdID:  "h-family",
			MemberID:     "m-emma-kid",
			RewardItemID: "rew-fam-icecream",
			PointsSpent:  75,
			Status:       models.RedemptionStatusRequested,
			RequestedAt:  now.Add(-3 * time.Hour).Format(time.RFC3339),
		},
	}

	activities := []models.ActivityLog{
		{
			ID:          "act-1",
			HouseholdID: "h-roommates",
			ActorID:     "m-sarah",
			EventType:   models.ActivityChoreCreated,
			EntityType:  "chore",
			EntityID:    "c-recycling-rr",
			Message:     "Sarah created weekly round-robin chore \"Recycling & Garbage to Curb\"",
			Read:        true,
			CreatedAt:   now.Add(-24 * time.Hour).Format(time.RFC3339),
		},
		{
			ID:          "act-2",
			HouseholdID: "h-roommates",
			ActorID:     "m-liam",
			EventType:   models.ActivitySwapProposed,
			EntityType:  "swap",
			EntityID:    "swap-seed-1",
			Message:     "Liam requested to swap \"Vacuum Living Room\" with Maya",
			Read:        false,
			CreatedAt:   now.Add(-5 * time.Hour).Format(time.RFC3339),
		},
		{
			ID:          "act-3",
			HouseholdID: "h-family",
			ActorID:     "m-leo-kid",
			EventType:   models.ActivityApprovalRequested,
			EntityType:  "chore",
			EntityID:    "c-fam-bedroom-leo",
			Message:     "Leo submitted \"Clean Up Bedroom & Put Away Toys\" for Parent verification",
			Read:        false,
			CreatedAt:   now.Add(-45 * time.Minute).Format(time.RFC3339),
		},
		{
			ID:          "act-4",
			HouseholdID: "h-family",
			ActorID:     "m-emma-kid",
			EventType:   models.ActivityRewardRedeemed,
			EntityType:  "reward",
			EntityID:    "rew-fam-icecream",
			Message:     "Emma redeemed 75 pts for \"Ice Cream Sundae Trip\"",
			Read:        false,
			CreatedAt:   now.Add(-3 * time.Hour).Format(time.RFC3339),
		},
	}

	comments := []models.ChoreComment{
		{
			ID:        "comm-1",
			ChoreID:   "c-vacuum-living",
			MemberID:  "m-liam",
			Message:   "Will definitely vacuum under the sofa cushions this time as requested!",
			CreatedAt: now.Add(-2 * time.Hour).Format(time.RFC3339),
		},
	}

	return households, members, chores, completions, swaps, rewards, redemptions, activities, comments
}
