apiVersion: v1
kind: Service
metadata:
  name: floci
  labels:
    app: floci
    app.kubernetes.io/name: floci
    app.kubernetes.io/part-of: choresync
spec:
  type: ClusterIP
  selector:
    app: floci
  ports:
    - port: 4566
      targetPort: 4566
      name: http
