// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID          string             `json:"id"`
	HouseholdID string             `json:"household_id"`
	RecipientID pgtype.Text        `json:"recipient_id"`
	ActorID     string             `json:"actor_id"`
	EventType   string             `json:"event_type"`
	EntityType  string             `json:"entity_type"`
	EntityID    string             `json:"entity_id"`
	Message     string             `json:"message"`
	Read        bool               `json:"read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Chore struct {
	ID                   string             `json:"id"`
	HouseholdID          string             `json:"household_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Category             string             `json:"category"`
	EffortPoints         int32              `json:"effort_points"`
	AssignmentType       string             `json:"assignment_type"`
	CurrentAssigneeID    pgtype.Text        `json:"current_assignee_id"`
	RotationMemberIds    []byte             `json:"rotation_member_ids"`
	CurrentRotationIndex pgtype.Int4        `json:"current_rotation_index"`
	RecurrenceType       string             `json:"recurrence_type"`
	RecurrenceRule       []byte             `json:"recurrence_rule"`
	DueDate              pgtype.Timestamptz `json:"due_date"`
	RequiresApproval     bool               `json:"requires_approval"`
	RequiresProof        bool               `json:"requires_proof"`
	Status               string             `json:"status"`
	CreatedBy            string             `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ChoreComment struct {
	ID        string             `json:"id"`
	ChoreID   string             `json:"chore_id"`
	MemberID  string             `json:"member_id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChoreCompletion struct {
	ID              string             `json:"id"`
	ChoreID         string             `json:"chore_id"`
	HouseholdID     string             `json:"household_id"`
	MemberID        string             `json:"member_id"`
	Status          string             `json:"status"`
	ProofNotes      pgtype.Text        `json:"proof_notes"`
	ProofPhotoUrl   pgtype.Text        `json:"proof_photo_url"`
	ApprovedBy      pgtype.Text        `json:"approved_by"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	PointsAwarded   int32              `json:"points_awarded"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
}

type ChoreSwapRequest struct {
	ID             string             `json:"id"`
	HouseholdID    string             `json:"household_id"`
	ChoreID        string             `json:"chore_id"`
	RequesterID    string             `json:"requester_id"`
	TargetMemberID pgtype.Text        `json:"target_member_id"`
	Status         string             `json:"status"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
}

type Household struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	InviteCode  string             `json:"invite_code"`
	DefaultMode string             `json:"default_mode"`
	AllowSwaps  bool               `json:"allow_swaps"`
	Timezone    string             `json:"timezone"`
	AdminPin    string             `json:"admin_pin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MagicLink struct {
	Token     string             `json:"token"`
	MemberID  string             `json:"member_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Member struct {
	ID                string             `json:"id"`
	HouseholdID       string             `json:"household_id"`
	Name              string             `json:"name"`
	Email             pgtype.Text        `json:"email"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Role              string             `json:"role"`
	PointsBalance     int32              `json:"points_balance"`
	TotalPointsEarned int32              `json:"total_points_earned"`
	Streak            int32              `json:"streak"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RewardItem struct {
	ID          string             `json:"id"`
	HouseholdID string             `json:"household_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PointsCost  int32              `json:"points_cost"`
	Icon        pgtype.Text        `json:"icon"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RewardRedemption struct {
	ID           string             `json:"id"`
	HouseholdID  string             `json:"household_id"`
	MemberID     string             `json:"member_id"`
	RewardItemID string             `json:"reward_item_id"`
	PointsSpent  int32              `json:"points_spent"`
	Status       string             `json:"status"`
	RequestedAt  pgtype.Timestamptz `json:"requested_at"`
	FulfilledAt  pgtype.Timestamptz `json:"fulfilled_at"`
}
