// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    id, household_id, recipient_id, actor_id, event_type, entity_type, entity_id, message, read, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, household_id, recipient_id, actor_id, event_type, entity_type, entity_id, message, read, created_at
`

type CreateActivityLogParams struct {
	ID          string             `json:"id"`
	HouseholdID string             `json:"household_id"`
	RecipientID pgtype.Text        `json:"recipient_id"`
	ActorID     string             `json:"actor_id"`
	EventType   string             `json:"event_type"`
	EntityType  string             `json:"entity_type"`
	EntityID    string             `json:"entity_id"`
	Message     string             `json:"message"`
	Read        bool               `json:"read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.ID,
		arg.HouseholdID,
		arg.RecipientID,
		arg.ActorID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.Message,
		arg.Read,
		arg.CreatedAt,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.RecipientID,
		&i.ActorID,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const createChore = `-- name: CreateChore :one
INSERT INTO chores (
    id, household_id, title, description, category, effort_points, assignment_type,
    current_assignee_id, rotation_member_ids, current_rotation_index, recurrence_type,
    recurrence_rule, due_date, requires_approval, requires_proof, status, created_by,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, household_id, title, description, category, effort_points, assignment_type, current_assignee_id, rotation_member_ids, current_rotation_index, recurrence_type, recurrence_rule, due_date, requires_approval, requires_proof, status, created_by, created_at, updated_at
`

type CreateChoreParams struct {
	ID                   string             `json:"id"`
	HouseholdID          string             `json:"household_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Category             string             `json:"category"`
	EffortPoints         int32              `json:"effort_points"`
	AssignmentType       string             `json:"assignment_type"`
	CurrentAssigneeID    pgtype.Text        `json:"current_assignee_id"`
	RotationMemberIds    []byte             `json:"rotation_member_ids"`
	CurrentRotationIndex pgtype.Int4        `json:"current_rotation_index"`
	RecurrenceType       string             `json:"recurrence_type"`
	RecurrenceRule       []byte             `json:"recurrence_rule"`
	DueDate              pgtype.Timestamptz `json:"due_date"`
	RequiresApproval     bool               `json:"requires_approval"`
	RequiresProof        bool               `json:"requires_proof"`
	Status               string             `json:"status"`
	CreatedBy            string             `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateChore(ctx context.Context, arg CreateChoreParams) (Chore, error) {
	row := q.db.QueryRow(ctx, createChore,
		arg.ID,
		arg.HouseholdID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.EffortPoints,
		arg.AssignmentType,
		arg.CurrentAssigneeID,
		arg.RotationMemberIds,
		arg.CurrentRotationIndex,
		arg.RecurrenceType,
		arg.RecurrenceRule,
		arg.DueDate,
		arg.RequiresApproval,
		arg.RequiresProof,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Chore
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.EffortPoints,
		&i.AssignmentType,
		&i.CurrentAssigneeID,
		&i.RotationMemberIds,
		&i.CurrentRotationIndex,
		&i.RecurrenceType,
		&i.RecurrenceRule,
		&i.DueDate,
		&i.RequiresApproval,
		&i.RequiresProof,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO chore_comments (
    id, chore_id, member_id, message, created_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, chore_id, member_id, message, created_at
`

type CreateCommentParams struct {
	ID        string             `json:"id"`
	ChoreID   string             `json:"chore_id"`
	MemberID  string             `json:"member_id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (ChoreComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.ChoreID,
		arg.MemberID,
		arg.Message,
		arg.CreatedAt,
	)
	var i ChoreComment
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.MemberID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createCompletion = `-- name: CreateCompletion :one
INSERT INTO chore_completions (
    id, chore_id, household_id, member_id, status, proof_notes, proof_photo_url,
    approved_by, rejection_reason, points_awarded, completed_at, verified_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, chore_id, household_id, member_id, status, proof_notes, proof_photo_url, approved_by, rejection_reason, points_awarded, completed_at, verified_at
`

type CreateCompletionParams struct {
	ID              string             `json:"id"`
	ChoreID         string             `json:"chore_id"`
	HouseholdID     string             `json:"household_id"`
	MemberID        string             `json:"member_id"`
	Status          string             `json:"status"`
	ProofNotes      pgtype.Text        `json:"proof_notes"`
	ProofPhotoUrl   pgtype.Text        `json:"proof_photo_url"`
	ApprovedBy      pgtype.Text        `json:"approved_by"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	PointsAwarded   int32              `json:"points_awarded"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) CreateCompletion(ctx context.Context, arg CreateCompletionParams) (ChoreCompletion, error) {
	row := q.db.QueryRow(ctx, createCompletion,
		arg.ID,
		arg.ChoreID,
		arg.HouseholdID,
		arg.MemberID,
		arg.Status,
		arg.ProofNotes,
		arg.ProofPhotoUrl,
		arg.ApprovedBy,
		arg.RejectionReason,
		arg.PointsAwarded,
		arg.CompletedAt,
		arg.VerifiedAt,
	)
	var i ChoreCompletion
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Status,
		&i.ProofNotes,
		&i.ProofPhotoUrl,
		&i.ApprovedBy,
		&i.RejectionReason,
		&i.PointsAwarded,
		&i.CompletedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (
    id, name, invite_code, default_mode, allow_swaps, timezone, admin_pin, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, invite_code, default_mode, allow_swaps, timezone, admin_pin, created_at, updated_at
`

type CreateHouseholdParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	InviteCode  string             `json:"invite_code"`
	DefaultMode string             `json:"default_mode"`
	AllowSwaps  bool               `json:"allow_swaps"`
	Timezone    string             `json:"timezone"`
	AdminPin    string             `json:"admin_pin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold,
		arg.ID,
		arg.Name,
		arg.InviteCode,
		arg.DefaultMode,
		arg.AllowSwaps,
		arg.Timezone,
		arg.AdminPin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.DefaultMode,
		&i.AllowSwaps,
		&i.Timezone,
		&i.AdminPin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (
    id, household_id, name, email, avatar_url, role, points_balance, total_points_earned, streak, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, household_id, name, email, avatar_url, role, points_balance, total_points_earned, streak, created_at, updated_at
`

type CreateMemberParams struct {
	ID                string             `json:"id"`
	HouseholdID       string             `json:"household_id"`
	Name              string             `json:"name"`
	Email             pgtype.Text        `json:"email"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Role              string             `json:"role"`
	PointsBalance     int32              `json:"points_balance"`
	TotalPointsEarned int32              `json:"total_points_earned"`
	Streak            int32              `json:"streak"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.Role,
		arg.PointsBalance,
		arg.TotalPointsEarned,
		arg.Streak,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.PointsBalance,
		&i.TotalPointsEarned,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRedemption = `-- name: CreateRedemption :one
INSERT INTO reward_redemptions (
    id, household_id, member_id, reward_item_id, points_spent, status, requested_at, fulfilled_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, household_id, member_id, reward_item_id, points_spent, status, requested_at, fulfilled_at
`

type CreateRedemptionParams struct {
	ID           string             `json:"id"`
	HouseholdID  string             `json:"household_id"`
	MemberID     string             `json:"member_id"`
	RewardItemID string             `json:"reward_item_id"`
	PointsSpent  int32              `json:"points_spent"`
	Status       string             `json:"status"`
	RequestedAt  pgtype.Timestamptz `json:"requested_at"`
	FulfilledAt  pgtype.Timestamptz `json:"fulfilled_at"`
}

func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (RewardRedemption, error) {
	row := q.db.QueryRow(ctx, createRedemption,
		arg.ID,
		arg.HouseholdID,
		arg.MemberID,
		arg.RewardItemID,
		arg.PointsSpent,
		arg.Status,
		arg.RequestedAt,
		arg.FulfilledAt,
	)
	var i RewardRedemption
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.RewardItemID,
		&i.PointsSpent,
		&i.Status,
		&i.RequestedAt,
		&i.FulfilledAt,
	)
	return i, err
}

const createReward = `-- name: CreateReward :one
INSERT INTO reward_items (
    id, household_id, title, description, points_cost, icon, is_active, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, household_id, title, description, points_cost, icon, is_active, created_at
`

type CreateRewardParams struct {
	ID          string             `json:"id"`
	HouseholdID string             `json:"household_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PointsCost  int32              `json:"points_cost"`
	Icon        pgtype.Text        `json:"icon"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReward(ctx context.Context, arg CreateRewardParams) (RewardItem, error) {
	row := q.db.QueryRow(ctx, createReward,
		arg.ID,
		arg.HouseholdID,
		arg.Title,
		arg.Description,
		arg.PointsCost,
		arg.Icon,
		arg.IsActive,
		arg.CreatedAt,
	)
	var i RewardItem
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.PointsCost,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSwap = `-- name: CreateSwap :one
INSERT INTO chore_swap_requests (
    id, household_id, chore_id, requester_id, target_member_id, status, reason, created_at, resolved_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, household_id, chore_id, requester_id, target_member_id, status, reason, created_at, resolved_at
`

type CreateSwapParams struct {
	ID             string             `json:"id"`
	HouseholdID    string             `json:"household_id"`
	ChoreID        string             `json:"chore_id"`
	RequesterID    string             `json:"requester_id"`
	TargetMemberID pgtype.Text        `json:"target_member_id"`
	Status         string             `json:"status"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) CreateSwap(ctx context.Context, arg CreateSwapParams) (ChoreSwapRequest, error) {
	row := q.db.QueryRow(ctx, createSwap,
		arg.ID,
		arg.HouseholdID,
		arg.ChoreID,
		arg.RequesterID,
		arg.TargetMemberID,
		arg.Status,
		arg.Reason,
		arg.CreatedAt,
		arg.ResolvedAt,
	)
	var i ChoreSwapRequest
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ChoreID,
		&i.RequesterID,
		&i.TargetMemberID,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const deleteChore = `-- name: DeleteChore :exec
DELETE FROM chores WHERE id = $1
`

func (q *Queries) DeleteChore(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChore, id)
	return err
}

const getActivitiesByHousehold = `-- name: GetActivitiesByHousehold :many
SELECT id, household_id, recipient_id, actor_id, event_type, entity_type, entity_id, message, read, created_at FROM activity_logs
WHERE household_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetActivitiesByHouseholdParams struct {
	HouseholdID string `json:"household_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) GetActivitiesByHousehold(ctx context.Context, arg GetActivitiesByHouseholdParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivitiesByHousehold, arg.HouseholdID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.RecipientID,
			&i.ActorID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChore = `-- name: GetChore :one
SELECT id, household_id, title, description, category, effort_points, assignment_type, current_assignee_id, rotation_member_ids, current_rotation_index, recurrence_type, recurrence_rule, due_date, requires_approval, requires_proof, status, created_by, created_at, updated_at FROM chores WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChore(ctx context.Context, id string) (Chore, error) {
	row := q.db.QueryRow(ctx, getChore, id)
	var i Chore
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.EffortPoints,
		&i.AssignmentType,
		&i.CurrentAssigneeID,
		&i.RotationMemberIds,
		&i.CurrentRotationIndex,
		&i.RecurrenceType,
		&i.RecurrenceRule,
		&i.DueDate,
		&i.RequiresApproval,
		&i.RequiresProof,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChoresByHousehold = `-- name: GetChoresByHousehold :many
SELECT id, household_id, title, description, category, effort_points, assignment_type, current_assignee_id, rotation_member_ids, current_rotation_index, recurrence_type, recurrence_rule, due_date, requires_approval, requires_proof, status, created_by, created_at, updated_at FROM chores WHERE household_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetChoresByHousehold(ctx context.Context, householdID string) ([]Chore, error) {
	rows, err := q.db.Query(ctx, getChoresByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chore{}
	for rows.Next() {
		var i Chore
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.EffortPoints,
			&i.AssignmentType,
			&i.CurrentAssigneeID,
			&i.RotationMemberIds,
			&i.CurrentRotationIndex,
			&i.RecurrenceType,
			&i.RecurrenceRule,
			&i.DueDate,
			&i.RequiresApproval,
			&i.RequiresProof,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByChore = `-- name: GetCommentsByChore :many
SELECT id, chore_id, member_id, message, created_at FROM chore_comments WHERE chore_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetCommentsByChore(ctx context.Context, choreID string) ([]ChoreComment, error) {
	rows, err := q.db.Query(ctx, getCommentsByChore, choreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChoreComment{}
	for rows.Next() {
		var i ChoreComment
		if err := rows.Scan(
			&i.ID,
			&i.ChoreID,
			&i.MemberID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletion = `-- name: GetCompletion :one
SELECT id, chore_id, household_id, member_id, status, proof_notes, proof_photo_url, approved_by, rejection_reason, points_awarded, completed_at, verified_at FROM chore_completions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCompletion(ctx context.Context, id string) (ChoreCompletion, error) {
	row := q.db.QueryRow(ctx, getCompletion, id)
	var i ChoreCompletion
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Status,
		&i.ProofNotes,
		&i.ProofPhotoUrl,
		&i.ApprovedBy,
		&i.RejectionReason,
		&i.PointsAwarded,
		&i.CompletedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, invite_code, default_mode, allow_swaps, timezone, admin_pin, created_at, updated_at FROM households WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHousehold(ctx context.Context, id string) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.DefaultMode,
		&i.AllowSwaps,
		&i.Timezone,
		&i.AdminPin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdByInviteCode = `-- name: GetHouseholdByInviteCode :one
SELECT id, name, invite_code, default_mode, allow_swaps, timezone, admin_pin, created_at, updated_at FROM households WHERE invite_code = $1 LIMIT 1
`

func (q *Queries) GetHouseholdByInviteCode(ctx context.Context, inviteCode string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByInviteCode, inviteCode)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.DefaultMode,
		&i.AllowSwaps,
		&i.Timezone,
		&i.AdminPin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholds = `-- name: GetHouseholds :many
SELECT id, name, invite_code, default_mode, allow_swaps, timezone, admin_pin, created_at, updated_at FROM households ORDER BY created_at ASC
`

func (q *Queries) GetHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.Query(ctx, getHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.DefaultMode,
			&i.AllowSwaps,
			&i.Timezone,
			&i.AdminPin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMagicLink = `-- name: GetMagicLink :one
SELECT token, member_id, created_at FROM magic_links WHERE token = $1 LIMIT 1
`

func (q *Queries) GetMagicLink(ctx context.Context, token string) (MagicLink, error) {
	row := q.db.QueryRow(ctx, getMagicLink, token)
	var i MagicLink
	err := row.Scan(&i.Token, &i.MemberID, &i.CreatedAt)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, household_id, name, email, avatar_url, role, points_balance, total_points_earned, streak, created_at, updated_at FROM members WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMember(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.PointsBalance,
		&i.TotalPointsEarned,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT id, household_id, name, email, avatar_url, role, points_balance, total_points_earned, streak, created_at, updated_at FROM members WHERE email = $1 LIMIT 1
`

func (q *Queries) GetMemberByEmail(ctx context.Context, email pgtype.Text) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByEmail, email)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.PointsBalance,
		&i.TotalPointsEarned,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembersByHousehold = `-- name: GetMembersByHousehold :many
SELECT id, household_id, name, email, avatar_url, role, points_balance, total_points_earned, streak, created_at, updated_at FROM members WHERE household_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetMembersByHousehold(ctx context.Context, householdID string) ([]Member, error) {
	rows, err := q.db.Query(ctx, getMembersByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.Role,
			&i.PointsBalance,
			&i.TotalPointsEarned,
			&i.Streak,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingApprovalsByHousehold = `-- name: GetPendingApprovalsByHousehold :many
SELECT id, chore_id, household_id, member_id, status, proof_notes, proof_photo_url, approved_by, rejection_reason, points_awarded, completed_at, verified_at FROM chore_completions
WHERE household_id = $1 AND status = 'pending_approval'
ORDER BY completed_at DESC
`

func (q *Queries) GetPendingApprovalsByHousehold(ctx context.Context, householdID string) ([]ChoreCompletion, error) {
	rows, err := q.db.Query(ctx, getPendingApprovalsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChoreCompletion{}
	for rows.Next() {
		var i ChoreCompletion
		if err := rows.Scan(
			&i.ID,
			&i.ChoreID,
			&i.HouseholdID,
			&i.MemberID,
			&i.Status,
			&i.ProofNotes,
			&i.ProofPhotoUrl,
			&i.ApprovedBy,
			&i.RejectionReason,
			&i.PointsAwarded,
			&i.CompletedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedemption = `-- name: GetRedemption :one
SELECT id, household_id, member_id, reward_item_id, points_spent, status, requested_at, fulfilled_at FROM reward_redemptions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRedemption(ctx context.Context, id string) (RewardRedemption, error) {
	row := q.db.QueryRow(ctx, getRedemption, id)
	var i RewardRedemption
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.RewardItemID,
		&i.PointsSpent,
		&i.Status,
		&i.RequestedAt,
		&i.FulfilledAt,
	)
	return i, err
}

const getRedemptionsByHousehold = `-- name: GetRedemptionsByHousehold :many
SELECT id, household_id, member_id, reward_item_id, points_spent, status, requested_at, fulfilled_at FROM reward_redemptions WHERE household_id = $1 ORDER BY requested_at DESC
`

func (q *Queries) GetRedemptionsByHousehold(ctx context.Context, householdID string) ([]RewardRedemption, error) {
	rows, err := q.db.Query(ctx, getRedemptionsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RewardRedemption{}
	for rows.Next() {
		var i RewardRedemption
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.RewardItemID,
			&i.PointsSpent,
			&i.Status,
			&i.RequestedAt,
			&i.FulfilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReward = `-- name: GetReward :one
SELECT id, household_id, title, description, points_cost, icon, is_active, created_at FROM reward_items WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReward(ctx context.Context, id string) (RewardItem, error) {
	row := q.db.QueryRow(ctx, getReward, id)
	var i RewardItem
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.PointsCost,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getRewardsByHousehold = `-- name: GetRewardsByHousehold :many
SELECT id, household_id, title, description, points_cost, icon, is_active, created_at FROM reward_items WHERE household_id = $1 ORDER BY points_cost ASC
`

func (q *Queries) GetRewardsByHousehold(ctx context.Context, householdID string) ([]RewardItem, error) {
	rows, err := q.db.Query(ctx, getRewardsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RewardItem{}
	for rows.Next() {
		var i RewardItem
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Title,
			&i.Description,
			&i.PointsCost,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSwap = `-- name: GetSwap :one
SELECT id, household_id, chore_id, requester_id, target_member_id, status, reason, created_at, resolved_at FROM chore_swap_requests WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSwap(ctx context.Context, id string) (ChoreSwapRequest, error) {
	row := q.db.QueryRow(ctx, getSwap, id)
	var i ChoreSwapRequest
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ChoreID,
		&i.RequesterID,
		&i.TargetMemberID,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getSwapsByHousehold = `-- name: GetSwapsByHousehold :many
SELECT id, household_id, chore_id, requester_id, target_member_id, status, reason, created_at, resolved_at FROM chore_swap_requests WHERE household_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetSwapsByHousehold(ctx context.Context, householdID string) ([]ChoreSwapRequest, error) {
	rows, err := q.db.Query(ctx, getSwapsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChoreSwapRequest{}
	for rows.Next() {
		var i ChoreSwapRequest
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ChoreID,
			&i.RequesterID,
			&i.TargetMemberID,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateAll = `-- name: TruncateAll :exec
TRUNCATE TABLE chore_comments, activity_logs, reward_redemptions, reward_items, chore_swap_requests, chore_completions, chores, members, households, magic_links CASCADE
`

func (q *Queries) TruncateAll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAll)
	return err
}

const updateChore = `-- name: UpdateChore :one
UPDATE chores SET
    title = $2,
    description = $3,
    category = $4,
    effort_points = $5,
    assignment_type = $6,
    current_assignee_id = $7,
    rotation_member_ids = $8,
    current_rotation_index = $9,
    recurrence_type = $10,
    recurrence_rule = $11,
    due_date = $12,
    requires_approval = $13,
    requires_proof = $14,
    status = $15,
    updated_at = NOW()
WHERE id = $1
RETURNING id, household_id, title, description, category, effort_points, assignment_type, current_assignee_id, rotation_member_ids, current_rotation_index, recurrence_type, recurrence_rule, due_date, requires_approval, requires_proof, status, created_by, created_at, updated_at
`

type UpdateChoreParams struct {
	ID                   string             `json:"id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Category             string             `json:"category"`
	EffortPoints         int32              `json:"effort_points"`
	AssignmentType       string             `json:"assignment_type"`
	CurrentAssigneeID    pgtype.Text        `json:"current_assignee_id"`
	RotationMemberIds    []byte             `json:"rotation_member_ids"`
	CurrentRotationIndex pgtype.Int4        `json:"current_rotation_index"`
	RecurrenceType       string             `json:"recurrence_type"`
	RecurrenceRule       []byte             `json:"recurrence_rule"`
	DueDate              pgtype.Timestamptz `json:"due_date"`
	RequiresApproval     bool               `json:"requires_approval"`
	RequiresProof        bool               `json:"requires_proof"`
	Status               string             `json:"status"`
}

func (q *Queries) UpdateChore(ctx context.Context, arg UpdateChoreParams) (Chore, error) {
	row := q.db.QueryRow(ctx, updateChore,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.EffortPoints,
		arg.AssignmentType,
		arg.CurrentAssigneeID,
		arg.RotationMemberIds,
		arg.CurrentRotationIndex,
		arg.RecurrenceType,
		arg.RecurrenceRule,
		arg.DueDate,
		arg.RequiresApproval,
		arg.RequiresProof,
		arg.Status,
	)
	var i Chore
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.EffortPoints,
		&i.AssignmentType,
		&i.CurrentAssigneeID,
		&i.RotationMemberIds,
		&i.CurrentRotationIndex,
		&i.RecurrenceType,
		&i.RecurrenceRule,
		&i.DueDate,
		&i.RequiresApproval,
		&i.RequiresProof,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChoreAssigneeAndStatus = `-- name: UpdateChoreAssigneeAndStatus :one
UPDATE chores
SET current_assignee_id = $2, status = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, household_id, title, description, category, effort_points, assignment_type, current_assignee_id, rotation_member_ids, current_rotation_index, recurrence_type, recurrence_rule, due_date, requires_approval, requires_proof, status, created_by, created_at, updated_at
`

type UpdateChoreAssigneeAndStatusParams struct {
	ID                string      `json:"id"`
	CurrentAssigneeID pgtype.Text `json:"current_assignee_id"`
	Status            string      `json:"status"`
}

func (q *Queries) UpdateChoreAssigneeAndStatus(ctx context.Context, arg UpdateChoreAssigneeAndStatusParams) (Chore, error) {
	row := q.db.QueryRow(ctx, updateChoreAssigneeAndStatus, arg.ID, arg.CurrentAssigneeID, arg.Status)
	var i Chore
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.EffortPoints,
		&i.AssignmentType,
		&i.CurrentAssigneeID,
		&i.RotationMemberIds,
		&i.CurrentRotationIndex,
		&i.RecurrenceType,
		&i.RecurrenceRule,
		&i.DueDate,
		&i.RequiresApproval,
		&i.RequiresProof,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChoreRotation = `-- name: UpdateChoreRotation :one
UPDATE chores
SET current_assignee_id = $2, current_rotation_index = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, household_id, title, description, category, effort_points, assignment_type, current_assignee_id, rotation_member_ids, current_rotation_index, recurrence_type, recurrence_rule, due_date, requires_approval, requires_proof, status, created_by, created_at, updated_at
`

type UpdateChoreRotationParams struct {
	ID                   string      `json:"id"`
	CurrentAssigneeID    pgtype.Text `json:"current_assignee_id"`
	CurrentRotationIndex pgtype.Int4 `json:"current_rotation_index"`
}

func (q *Queries) UpdateChoreRotation(ctx context.Context, arg UpdateChoreRotationParams) (Chore, error) {
	row := q.db.QueryRow(ctx, updateChoreRotation, arg.ID, arg.CurrentAssigneeID, arg.CurrentRotationIndex)
	var i Chore
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.EffortPoints,
		&i.AssignmentType,
		&i.CurrentAssigneeID,
		&i.RotationMemberIds,
		&i.CurrentRotationIndex,
		&i.RecurrenceType,
		&i.RecurrenceRule,
		&i.DueDate,
		&i.RequiresApproval,
		&i.RequiresProof,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompletionApproval = `-- name: UpdateCompletionApproval :one
UPDATE chore_completions
SET status = $2, approved_by = $3, rejection_reason = $4, verified_at = $5
WHERE id = $1
RETURNING id, chore_id, household_id, member_id, status, proof_notes, proof_photo_url, approved_by, rejection_reason, points_awarded, completed_at, verified_at
`

type UpdateCompletionApprovalParams struct {
	ID              string             `json:"id"`
	Status          string             `json:"status"`
	ApprovedBy      pgtype.Text        `json:"approved_by"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) UpdateCompletionApproval(ctx context.Context, arg UpdateCompletionApprovalParams) (ChoreCompletion, error) {
	row := q.db.QueryRow(ctx, updateCompletionApproval,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
		arg.RejectionReason,
		arg.VerifiedAt,
	)
	var i ChoreCompletion
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Status,
		&i.ProofNotes,
		&i.ProofPhotoUrl,
		&i.ApprovedBy,
		&i.RejectionReason,
		&i.PointsAwarded,
		&i.CompletedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const updateHouseholdSettings = `-- name: UpdateHouseholdSettings :one
UPDATE households
SET default_mode = $2, allow_swaps = $3, timezone = $4, admin_pin = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, invite_code, default_mode, allow_swaps, timezone, admin_pin, created_at, updated_at
`

type UpdateHouseholdSettingsParams struct {
	ID          string `json:"id"`
	DefaultMode string `json:"default_mode"`
	AllowSwaps  bool   `json:"allow_swaps"`
	Timezone    string `json:"timezone"`
	AdminPin    string `json:"admin_pin"`
}

func (q *Queries) UpdateHouseholdSettings(ctx context.Context, arg UpdateHouseholdSettingsParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHouseholdSettings,
		arg.ID,
		arg.DefaultMode,
		arg.AllowSwaps,
		arg.Timezone,
		arg.AdminPin,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.DefaultMode,
		&i.AllowSwaps,
		&i.Timezone,
		&i.AdminPin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberStats = `-- name: UpdateMemberStats :one
UPDATE members
SET points_balance = $2, total_points_earned = $3, streak = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, household_id, name, email, avatar_url, role, points_balance, total_points_earned, streak, created_at, updated_at
`

type UpdateMemberStatsParams struct {
	ID                string `json:"id"`
	PointsBalance     int32  `json:"points_balance"`
	TotalPointsEarned int32  `json:"total_points_earned"`
	Streak            int32  `json:"streak"`
}

func (q *Queries) UpdateMemberStats(ctx context.Context, arg UpdateMemberStatsParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberStats,
		arg.ID,
		arg.PointsBalance,
		arg.TotalPointsEarned,
		arg.Streak,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.PointsBalance,
		&i.TotalPointsEarned,
		&i.Streak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRedemptionStatus = `-- name: UpdateRedemptionStatus :one
UPDATE reward_redemptions
SET status = $2, fulfilled_at = $3
WHERE id = $1
RETURNING id, household_id, member_id, reward_item_id, points_spent, status, requested_at, fulfilled_at
`

type UpdateRedemptionStatusParams struct {
	ID          string             `json:"id"`
	Status      string             `json:"status"`
	FulfilledAt pgtype.Timestamptz `json:"fulfilled_at"`
}

func (q *Queries) UpdateRedemptionStatus(ctx context.Context, arg UpdateRedemptionStatusParams) (RewardRedemption, error) {
	row := q.db.QueryRow(ctx, updateRedemptionStatus, arg.ID, arg.Status, arg.FulfilledAt)
	var i RewardRedemption
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.RewardItemID,
		&i.PointsSpent,
		&i.Status,
		&i.RequestedAt,
		&i.FulfilledAt,
	)
	return i, err
}

const updateSwapStatus = `-- name: UpdateSwapStatus :one
UPDATE chore_swap_requests
SET status = $2, resolved_at = $3
WHERE id = $1
RETURNING id, household_id, chore_id, requester_id, target_member_id, status, reason, created_at, resolved_at
`

type UpdateSwapStatusParams struct {
	ID         string             `json:"id"`
	Status     string             `json:"status"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) UpdateSwapStatus(ctx context.Context, arg UpdateSwapStatusParams) (ChoreSwapRequest, error) {
	row := q.db.QueryRow(ctx, updateSwapStatus, arg.ID, arg.Status, arg.ResolvedAt)
	var i ChoreSwapRequest
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ChoreID,
		&i.RequesterID,
		&i.TargetMemberID,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const upsertMagicLink = `-- name: UpsertMagicLink :one
INSERT INTO magic_links (token, member_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET created_at = EXCLUDED.created_at
RETURNING token, member_id, created_at
`

type UpsertMagicLinkParams struct {
	Token     string             `json:"token"`
	MemberID  string             `json:"member_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertMagicLink(ctx context.Context, arg UpsertMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, upsertMagicLink, arg.Token, arg.MemberID, arg.CreatedAt)
	var i MagicLink
	err := row.Scan(&i.Token, &i.MemberID, &i.CreatedAt)
	return i, err
}
