// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateChore(ctx context.Context, arg CreateChoreParams) (Chore, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (ChoreComment, error)
	CreateCompletion(ctx context.Context, arg CreateCompletionParams) (ChoreCompletion, error)
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (RewardRedemption, error)
	CreateReward(ctx context.Context, arg CreateRewardParams) (RewardItem, error)
	CreateSwap(ctx context.Context, arg CreateSwapParams) (ChoreSwapRequest, error)
	DeleteChore(ctx context.Context, id string) error
	GetActivitiesByHousehold(ctx context.Context, arg GetActivitiesByHouseholdParams) ([]ActivityLog, error)
	GetChore(ctx context.Context, id string) (Chore, error)
	GetChoresByHousehold(ctx context.Context, householdID string) ([]Chore, error)
	GetCommentsByChore(ctx context.Context, choreID string) ([]ChoreComment, error)
	GetCompletion(ctx context.Context, id string) (ChoreCompletion, error)
	GetHousehold(ctx context.Context, id string) (Household, error)
	GetHouseholdByInviteCode(ctx context.Context, inviteCode string) (Household, error)
	GetHouseholds(ctx context.Context) ([]Household, error)
	GetMagicLink(ctx context.Context, token string) (MagicLink, error)
	GetMember(ctx context.Context, id string) (Member, error)
	GetMemberByEmail(ctx context.Context, email pgtype.Text) (Member, error)
	GetMembersByHousehold(ctx context.Context, householdID string) ([]Member, error)
	GetPendingApprovalsByHousehold(ctx context.Context, householdID string) ([]ChoreCompletion, error)
	GetRedemption(ctx context.Context, id string) (RewardRedemption, error)
	GetRedemptionsByHousehold(ctx context.Context, householdID string) ([]RewardRedemption, error)
	GetReward(ctx context.Context, id string) (RewardItem, error)
	GetRewardsByHousehold(ctx context.Context, householdID string) ([]RewardItem, error)
	GetSwap(ctx context.Context, id string) (ChoreSwapRequest, error)
	GetSwapsByHousehold(ctx context.Context, householdID string) ([]ChoreSwapRequest, error)
	TruncateAll(ctx context.Context) error
	UpdateChore(ctx context.Context, arg UpdateChoreParams) (Chore, error)
	UpdateChoreAssigneeAndStatus(ctx context.Context, arg UpdateChoreAssigneeAndStatusParams) (Chore, error)
	UpdateChoreRotation(ctx context.Context, arg UpdateChoreRotationParams) (Chore, error)
	UpdateCompletionApproval(ctx context.Context, arg UpdateCompletionApprovalParams) (ChoreCompletion, error)
	UpdateHouseholdSettings(ctx context.Context, arg UpdateHouseholdSettingsParams) (Household, error)
	UpdateMemberStats(ctx context.Context, arg UpdateMemberStatsParams) (Member, error)
	UpdateRedemptionStatus(ctx context.Context, arg UpdateRedemptionStatusParams) (RewardRedemption, error)
	UpdateSwapStatus(ctx context.Context, arg UpdateSwapStatusParams) (ChoreSwapRequest, error)
	UpsertMagicLink(ctx context.Context, arg UpsertMagicLinkParams) (MagicLink, error)
}

var _ Querier = (*Queries)(nil)
